# Generated by Django 3.0.4 on 2020-04-28 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flatapp', '0004_auto_20200422_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('property_price', models.FloatField()),
                ('booking_amount', models.FloatField()),
                ('property_image1', models.ImageField(upload_to='property/%Y/%m/%d')),
                ('property_image2', models.ImageField(upload_to='property/%Y/%m/%d')),
                ('property_image3', models.ImageField(upload_to='property/%Y/%m/%d')),
                ('property_image4', models.ImageField(upload_to='property/%Y/%m/%d')),
                ('property_status', models.CharField(max_length=250)),
                ('area', models.FloatField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('is_Air_Conditioning', models.BooleanField()),
                ('is_Gym', models.BooleanField()),
                ('is_Laundry_room', models.BooleanField()),
                ('is_TV_Cable', models.BooleanField()),
                ('is_Wifi', models.BooleanField()),
                ('is_Parking', models.BooleanField()),
                ('is_Swimming_Pool', models.BooleanField()),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatapp.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
