# Generated by Django 3.0.4 on 2020-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0006_auto_20200429_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_prperty',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
