# Generated by Django 3.0.4 on 2020-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0007_add_prperty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='full_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='proof/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='register_table',
            name='insta',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='qualifictn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='fb',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='twitr',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
