# Generated by Django 3.0.4 on 2020-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0008_auto_20200504_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Property_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('contact_number', models.IntegerField(unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Send Message To Owner',
            },
        ),
    ]
