# Generated by Django 3.0.4 on 2020-05-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0011_auto_20200514_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
